version: "3.3"

services:
  web:
    build: .
    command: python wsgi.py
    volumes:
      - .:/code
    ports:
      - "5005:5005"
    depends_on:
      - db
#    environment:
#      DATABASE_URL: postgres://naruto:voloda2000@db:5432/flask_test
  db:
    image: postgres
    restart: always
    volumes:
      - .data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flask_test
      - POSTGRES_USER=naruto
      - POSTGRES_PASSWORD=voloda2000
